//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatsDogsEgorPopelyuk_320P.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animal
    {
        public int ID_animal { get; set; }
        public string Exposition { get; set; }
        public Nullable<int> ID_animal_type { get; set; }
        public byte[] Image_animal { get; set; }
        public Nullable<int> ID_users { get; set; }
    
        public virtual AnimalType AnimalType { get; set; }
        public virtual Users Users { get; set; }
    }
}
